### PR TITLE
change encoding to UTF8

### PR DESCRIPTION
**Pull request by rfrelat**

### CODE REVIEW

**Comment by l-gorman** [comment]
Cheers for the PR @rfrelat 🙂 

I have made a few changes to the PR, was wondering whether you could check if you are happy with them:

1. I moved your function from `load_rhomis_csv` to `clean_column_names`. This makes it much easier to add extra checks to the test suite.
2. I have added tests to make sure the function works as expected
3. I have also added warning messages, specifying which column names were duplicated, and how these were dealt with
4. I have gone through the rest of the package and suppressed messages from `read_csv` to also minimise the extra printing junk.

Finally, I just want to check I understand what you were hoping to achieve with the duplicates based off of the behaviour I observed when I wrote the tests for the function. From what I have seen, if there is a duplicate, it prepends the duplicated column with an underscore. So column names `crop_name` and `crop_name` would become `crop_name` and `_crop_name`. Is that right?

Thanks again for the PR, let me know if you are happy with the changes, and if so I can merge these changes in!

**Comment by rfrelat** [comment]
I like your idea @l-gorman  of incorporating the renaming of duplicates column in clean_column_names().
But the changes in the function do not make what I originally wanted (maybe only because I deal with complicated dataset).

In many cases, what I have is something like:
xx/yy/dryseason_animal_graze_shortage/jan
xx/yy/dryseason_animal_graze_shortage/feb
xx/yy/wetseason_animal_graze_shortage/jan
zz/foodshortagetime_months_which/jan
ww/Wild_Foods_details/collect_when/jan
ww/Fruits_details/collect_when/jan

What I want is something like:
dryseason_animal_graze_shortage_jan
dryseason_animal_graze_shortage_feb
wetseason_animal_graze_shortage_jan
foodshortagetime_months_which_jan
foodshortagetime_months_which_feb
wild_foods_details_collect_when_jan
fruits_details_collect_when_jan

But in fact, what I coded would keep the first item as simplified name (the first 'jan' would stay 'jan', which is not ideal). So what would be needed is to keep the names before the separation_list loop, and then use these names in the while loop.

By the way, a while loop is already tricky (my hypothesis to avoid infinite loop was that there was no duplicates column in the original column name = fully written). Now you have made it recursive (we call clean_column_names() in the while loop), it´s getting even trickier ... Maybe there is an easier solution. 

Or maybe we forget about that and do it at a later time.

**Comment by l-gorman** [comment]
Great point romain, that is really sensible. I think this commit now implements the fix you were hoping for. I would take a look at the tests just to make sure. 

I have added one caveat, if the while look has to search through 5 sets of slashes, then  I add underscores to the beginning (to stop it infinitely searching backwards or returning an error. This is incredibly quite unlikely to happen but thought I would include just incase

**Comment by l-gorman** [comment]
@rfrelat, thanks for the suggestion! Let me know if it works for you and if so I'll merge in 🙂

**Comment by rfrelat** [comment]
Yes you can merge in, it works for me. Thanks again :)

**Comment by l-gorman** [comment]
Merged now! Thanks so much!

**Pull request merged**
